name       : kcmutils
version    : 5.80.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kcmutils-5.80.0.tar.xz : 8c93b1a865bcfe0aa85b8ac59b7b0f214aa5fdc5767ee51657657360a8739e59
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kpackage-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kservice-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
