name       : kcmutils
version    : 5.59.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kcmutils-5.59.0.tar.xz : 7468a2dddcfc3dde91898f76585d66f1d2620b2c341c4b6c85de16bea403a5ff
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
