name       : kcmutils
version    : 5.79.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kcmutils-5.79.0.tar.xz : 73d286b84ad32e3fa350b667993a6db731ee4c7e878d0a0cf9f5c81933423ef3
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kpackage-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kservice-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
