name       : kcmutils
version    : 5.67.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kcmutils-5.67.0.tar.xz : ffa61de96a5b11d29b871cd9caf075995236ad3dd432738fb774c97197d9ee8b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
