name       : kcmutils
version    : 5.36.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.36/kcmutils-5.36.0.tar.xz : df21667f6dae44707d13e51780ffe157fd0a29d4b946b14876a2a96633b32e66
license    : LGPL-2.1
component  : programming
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
