name       : kcmutils
version    : 5.85.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kcmutils-5.85.0.tar.xz : 20e8a32f1f22bc0afc682b694c2d6d8333c9de796845904685269fb3719ece93
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kpackage-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kservice-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
