name       : kcmutils
version    : 5.45.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kcmutils-5.45.0.tar.xz : f835e25d659f3ec96305e150649ca112c31a1b5f4937e5659a370b9832170870
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
