name       : kcmutils
version    : 5.93.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/kcmutils-5.93.0.tar.xz : 1445f978b7ffd69fd7c25d965812755679c4fdba23eb9837da37a8b5b2d30d6d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kpackage-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kservice-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
