name       : kcmutils
version    : 5.69.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kcmutils-5.69.0.tar.xz : 0213655963d02b5e66918d242d71f08b9cde7c9040a95518437cdefa0959187d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
