name       : kcmutils
version    : 5.60.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kcmutils-5.60.0.tar.xz : 22226ca10caedc6021b966a26a45096f30837ca9eedcc97479e30f950abc7b8c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
