name       : kcmutils
version    : 5.46.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kcmutils-5.46.0.tar.xz : 3bd8f7c3bc58d16a4e192729da67ea3ba4b3c19b535da5311f6d94ea86d59b2f
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kservice-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
