name       : kcmutils
version    : 5.96.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kcmutils-5.96.0.tar.xz : 88819fe343776a1819eecddbe2caa936ea2e9fbbfd2a155c46b82525e748ce6d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for KDE System Settings modules
description: |
    KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.KCMUtils provides various classes to work with KCModules. KCModules can be created with the KConfigWidgets framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kdeclarative-devel
    - kguiaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kpackage-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kservice-devel
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
